export const Dummy = [
  { 
    id:1,
    image:"img/amanda-jones-V1LGk9cQMts-unsplash-removebg-preview.png",
    text:"Red Tape" ,
    price:"37$",
  }, 
  { 
    id:2,
    image:"img/adrian-hernandez-QKP-fXB615w-unsplash-removebg-preview.png",
    text:"Roadster" ,
    price:"30$",
  }, 
  { 
    id:3,
    image:"img/brian-hall-x5aavOm7PFc-unsplash-removebg-preview.png",
    text:"Catwalk" ,
    price:"60$",
  }, 
  { 
    id:4,
    image:"img/linda-xu-fUEP0djb1hA-unsplash-removebg-preview.png",
    text:"Provogue" ,
    price:"50$",
  }, 
  { 
    id:5,
    image:"img/malvestida-magazine-DMl5gG0yWWY-unsplash-removebg-preview.png",
    text:"Skecher" ,
    price:"45$",
  }, 
  { 
    id:6,
    image:"img/ian-bevis-IJjfPInzmdk-unsplash-removebg-preview.png",
    text:"Wonkers" ,
    price:"30$",
  }, 
  { 
    id:7,
    image:"img/kristian-egelund-vJgJLzWmXDA-unsplash-removebg-preview.png",
    text:"Apex",
    price:"35$",
  }, 
  { 
    id:8,
    image:"img/ryan-plomp-jvoZ-Aux9aw-unsplash-removebg-preview.png",
    text:"Crox" ,
    price:"25$",
  }, 
  { 
    id:9,
    image:"img/jonathan-sanchez-QarKZGj0mzk-unsplash-removebg-preview.png",
    text:"Maniac" ,
    price:"7$",
  }, 
  { 
    id:10,
    image:"img/jonathan-sanchez-ZX5hQiUmDPY-unsplash-removebg-preview.png",
    text:"Heutrap",
    price:"8$",
  }, 
  { 
    id:11,
    image:"img/faith-yarn-Wr0TpKqf26s-unsplash-removebg-preview.png",
    text:"Nautica" ,
    price:"8$",
  }, 
  { 
    id:12,
    image:"img/alex-haigh-fEt6Wd4t4j0-unsplash-removebg-preview.png",
    text:"Roadmonkey" ,
    price:"6$",
  }, 
  { 
    id:13,
    image:"img/john-torcasio-TJrkkhdB39E-unsplash-removebg-preview.png",
    text:"Skmei Mens Watch" ,
    price:"25$",
  }, 
  { 
    id:14,
    image:"img/john-torcasio-OvcuGfIwHuc-unsplash-removebg-preview.png",
    text:"Navy's Men watch" ,
    price:"36$",
  }, 
  { 
    id:15,
    image:"img/john-torcasio-133Vq4tTpBQ-unsplash-removebg-preview.png",
    text:"Edge Mens watch" ,
    price:"34$",
  }, 
  { 
    id:16,
    image:"img/nick-karvounis-4CsUasi5H-Y-unsplash-removebg-preview.png",
    text:"Navy Men's Watch" ,
    price:"45$",
  }, 
  { 
    id:17,
    image:"img/daniel-korpai-oOlPR-Fwd7A-unsplash-removebg-preview.png",
    text:"Hwtwo Smart Watch" ,
    price:"60$",
  }, 
  { 
    id:18,
    image:"img/ivan-shilov-KiAYZZjpjkQ-unsplash-removebg-preview.png",
    text:"D2N1 Smartwatch" ,
    price:"45$",
  }, 
  { 
    id:19,
    image:"img/infino-photography-URlXm2Kx6uI-unsplash-removebg-preview.png",
    text:"Fossil Smartwatch" ,
    price:"50$",
  }, 
  { 
    id:20,
    image:"img/infino-photography-LAacfd1Hn8g-unsplash-removebg-preview.png",
    text:"Amazfit Smarteatch" ,
    price:"35$",
  }, 
  { 
    id:21,
    image:"img/shelly-pence-yjsdjOswsVs-unsplash-removebg-preview.png",
    text:"Louiswill Glass" ,
    price:"5$",
  }, 
  { 
    id:22,
    image:"img/david-suarez-nYJWo9fycwQ-unsplash-removebg-preview.png",
    text:"Magnetic clip glass" ,
    price:"6$",
  }, 
  { 
    id:23,
    image:"img/lucas-george-wendt-3xtCeUhqZWE-unsplash-removebg-preview.png",
    text:"Galvanaze glass" ,
    price:"5$",
  }, 
  { 
    id:24,
    image:"img/error-420-98SBGzseO-8-unsplash-removebg-preview.png",
    text:"Bentley Glass" ,
    price:"7$",
  }, 
  { 
    id:25,
    image:"img/laura-chouette-WOltc48__wI-unsplash-removebg-preview.png",
    text:"Vetton Bag" ,
    price:"430$",
  }, 
  { 
    id:26,
    image:"img/laura-chouette-RycLeDdrWJ0-unsplash-removebg-preview.png",
    text:"Coopers Bag" ,
    price:"270$",
  }, 
  { 
    id:27,
    image:"img/irene-kredenets-tcVH_BwHtrc-unsplash-removebg-preview.png",
    text:"Louis Vetton" ,
    price:"1250$",
  }, 
  { 
    id:28,
    image:"img/irene-kredenets-qjyNCxmun3E-unsplash__1_-removebg-preview.png",
    text:"Gucci" ,
    price:"650$",
  }, 
  { 
    id:29,
    image:"img/miguel-andrade-potCPE_Cw8A-unsplash-removebg-preview.png",
    text:"Fog" ,
    price:"50$",
  }, 
  { 
    id:30,
    image:"img/sikandar-ali-ANY7xVE0nkM-unsplash-removebg-preview.png",
    text:"Wild Stone" ,
    price:"70$",
  }, 
  { 
    id:31,
    image:"img/abdullah-ahmad-nYI7CaDWh-w-unsplash-removebg-preview.png",
    text:"Game of paris" ,
    price:"45$",
  }, 
  { 
    id:32,
    image:"img/mitra-jml-vPVBZxfyHOQ-unsplash-removebg-preview.png",
    text:"All Nauman" ,
    price:"46$",
  }, 
  { 
    id:33,
    image:"img/ali-bakhtiari-1CuZk0zMSjM-unsplash-removebg-preview.png",
    text:"Appeal Cologne" ,
    price:"60$",
  }, 
  { 
    id:34,
    image:"img/ali-bakhtiari-7ic3yF64FS8-unsplash-removebg-preview.png",
    text:"Red Dragon" ,
    price:"46$",
  }, 
  { 
    id:35,
    image:"img/klim-musalimov-92kIaT5A-W0-unsplash-removebg-preview.png",
    text:"Cherry Love" ,
    price:"45$",
  }, 
  { 
    id:36,
    image:"img/joice-kelly-45An7hKX510-unsplash-removebg-preview.png",
    text:"Loreal Heart" ,
    price:"70$",
  } 
];



